#ifndef DEF_SUNKEN_TEMPLE_H
#define DEF_SUNKEN_TEMPLE_H

#define TROLLBOSS1_DEATH 1
#define TROLLBOSS2_DEATH 2
#define TROLLBOSS3_DEATH 3
#define TROLLBOSS4_DEATH 4
#define TROLLBOSS5_DEATH 5
#define TROLLBOSS6_DEATH 6
#define JAMMALAN_DEATH 7
#define MORPHAZ_DEATH 8
#define HAZZAS_DEATH 9
#define ERANIKUS_DEATH 10
#define ATALALARION_DEATH 11 //optional

#define NPC_MALFURION 15362

#define EVENT_ATALAI_STATE 1
#define EVENT_HAKKAR_STATE 2
#define TYPE_ATALARION 3
#define TYPE_MALFURION 4
#define TYPE_HAKKAR 5

#endif

