#ifndef DEF_OCULUS_H
#define DEF_OCULUS_H

enum Data
{
    DATA_DRAKOS_EVENT,
    DATA_VAROS_EVENT,
    DATA_UROM_EVENT,
    DATA_EREGOS_EVENT
};

enum Data64
{
    DATA_DRAKOS,
    DATA_VAROS,
    DATA_UROM,
    DATA_EREGOS
};

enum Bosses
{
    CREATURE_DRAKOS        = 27654,
    CREATURE_VAROS         = 27447,
    CREATURE_UROM          = 27655,
    CREATURE_EREGOS        = 27656,
    CREATURE_PROEC	   = 28012,
    CACHE_OF_EREGOS	   = 191349,
    CACHE_OF_EREGOS_H	   = 193603
};

#endif
